update: github workflows and documentation
kommitters/tickspot.js pull request #103
Opened 2022-07-29 21:14 UTC by SanGeeky

## Objective
Update Github Workflows related to Continuous Integration and publishing the package to npm. Furthermore, updates the documentation pertaining to LICENSE and CONTRIBUTING.

This PR improves the repository before publishing the initial release of the project.

2022-07-29 22:15 UTC, miguelnietoa requested changes
Hi there @SanGeeky, some changes are required!

2022-07-29 22:15 UTC, miguelnietoa commented on CONTRIBUTING.md
> +  * To create a production bundle, run `npm run build`.
These commands do not exist under "scripts" inside the `package.json`. Do you consider they're required? 🤔

2022-07-29 22:15 UTC, miguelnietoa commented on CONTRIBUTING.md
>    * Please avoid working directly on the `main|master` branch.
Let's remove the `master` branch
```suggestion
  * This is usually the `main` branch.
  * Please avoid working directly on the `main` branch.
```

2022-08-02 17:05 UTC, SanGeeky commented on CONTRIBUTING.md
> +  * To create a production bundle, run `npm run build`.
Not for now, maybe could be an improvement in the future.

2022-08-02 21:53 UTC, miguelnietoa requested changes
Please remove `master` from lines 31 and 44 in the `CONTRIBUTING.md` file, and that's it!

2022-08-03 21:01 UTC, miguelnietoa approved these changes

2022-08-03 21:25 UTC, merged