Update issue templates
kommitters/tickspot.js pull request #105
Opened 2022-07-29 21:34 UTC by jhonatan-kmt

## Description
Update bug report template to project contributors will automatically see the template's contents in the issue body

### Objective
Add/update issue templates

### CheckList
- [x] Issue templates are up to date

2022-07-29 22:22 UTC, miguelnietoa requested changes
Hi there @jhonatan-kmt 
I consider we should add an issue template for Epics, too. What do you think? 🤔

2022-07-29 22:49 UTC, jhonatan-kmt commented
I liked it, I will implement the new template

2022-08-01 15:29 UTC, miguelnietoa requested changes
Looks good this Epic template! 👌🏻 
Please, see if the suggestions sound good to you @jhonatan-kmt

2022-08-01 15:29 UTC, miguelnietoa commented on .github/ISSUE_TEMPLATE/epic_feature.md
> +assignees: ''
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion (non-blocking):** ‏An Epic is not always a feature, we could have an Epic for a list of fixes or refactors. So, what about just keeping "Epic" instead of "Epic feature"?

```suggestion
name: 🎯 Epic
about: Tell us about this new Epic
title: ''
labels: '🎯 Epic'
assignees: ''
```

2022-08-01 15:29 UTC, miguelnietoa commented on .github/ISSUE_TEMPLATE/epic_feature.md
> +If you consider, you can mention a related issue.
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion (non-blocking):** ‏Maybe this comment is more understandable, do you agree?

```suggestion
This checklist can be taken as the subtasks to solve this Epic.
Whenever possible, mention the related issues.
```

2022-08-01 16:11 UTC, jhonatan-kmt commented on .github/ISSUE_TEMPLATE/epic_feature.md
> +assignees: ''
Ok, I hadn't thought that an Epic could be something other than a feature.
I will change it. :+1:

2022-08-01 16:56 UTC, miguelnietoa approved these changes
👏🏻

2022-08-03 16:48 UTC, merged