#64 Create user
kommitters/tickspot.js pull request #109
Opened 2022-08-01 16:29 UTC by SergioGueruiz

:information_source:  This issue is part of the Epic https://github.com/kommitters/tickspot.js/issues/59.
Objective

Create a module to create a user from the Tickspot API.

Documentation:

- [POST/users.json](https://github.com/tick/tick-api/blob/master/sections/users.md#create-user)

CheckList

- [ ] Create a method to create a user.
- [ ] Create tests.

2022-08-01 19:25 UTC, einerzg commented
@miguelnietoa please help me with your review here!!!

2022-08-02 15:28 UTC, miguelnietoa commented on src/v2/resources/users.js
> +      ...((billableRate && { billableRate }) || { billableRate: '0.0' }),
The fields `admin` and `billable_rate` seems to be ignored by the Tick API, please review if these fields are allowed in the create-user endpoint.

2022-08-04 15:33 UTC, SergioGueruiz commented
## Update
The fields `admin` and `billable_rate` are ignored by the API when we try to create an user, so we decide to delete them from the request.

2022-08-04 15:51 UTC, miguelnietoa requested changes

2022-08-04 15:51 UTC, miguelnietoa commented on src/v2/resources/users.js
> +   *    [Optional] billableRate
Please remove `admin` and `billabeRate` from function documentation!

2022-08-04 15:51 UTC, miguelnietoa commented on src/v2/resources/users.js
> +    };
We should keep the **camelCase** style in the parameters of the functions, however at the moment of building the body, the API receives the fields in **snake_case**

2022-08-04 15:54 UTC, miguelnietoa commented
> ## Update
> The fields `admin` and `billable_rate` are ignored by the API when we try to create an user, so we decide to delete them from the request.

Agree, I have reported an issue so let's keep alert to the response!
In the meantime, let's leave those fields outside.

Issue: https://github.com/tick/tick-api/issues/56

2022-08-04 16:12 UTC, miguelnietoa approved these changes
Thanks for your contribution, @SergioGueruiz! 🎉 🎉

2022-08-04 16:14 UTC, miguelnietoa commented
@SergioGueruiz, could you please sign all commits? This is a security rule to merge pull requests 😅

2022-08-04 16:52 UTC, miguelnietoa approved these changes

2022-08-04 16:53 UTC, merged