#14 List entries (Tickspot)
kommitters/tickspot.js pull request #30
Opened 2021-11-12 00:52 UTC by estebancordoba

## Related issue 
- #14  

## Description
Create a method to retrieve entries from Tickspot API.

## Proposed changes
- Create a list entries method in the Tickspot Client module.

## Additional Info
- [Get entries](https://github.com/tick/tick-api/blob/master/sections/entries.md#get-entries)

2022-01-04 19:39 UTC, JoseCastroA requested changes
@estebancordoba I left you some comments, please let me know if there is any question or something we can review together.

cc/ @brayvasq

2022-01-04 19:39 UTC, JoseCastroA commented on test/v2/entries.test.js
> +    it('should return the list of tick entries', async () => {
@estebancordoba Why is successful? 

Could be` describe('when params are correct/completed')` and `it('should return the list of tick entries')`

When we run the tests, all the text is concatenated. In this case:` when API call is successful it should return the list of tick entries` It can be a bit redundant.

2022-01-04 19:39 UTC, JoseCastroA commented on test/v2/entries.test.js
> +    it('Should reject with an error', async () => {
@estebancordoba Same here, the text is: `when list method returns an error it Should reject with an error` 
It's redundant.

Also, be careful are the capital letters. -> `it('Should`

2022-01-04 19:39 UTC, JoseCastroA commented on test/v2/entries.test.js
> +    it('Should reject with an error because of missing parameters', async () => {
@estebancordoba Same here.

What if: `when are missing parameters -- it returns 'required param startDate is missing'`?

What do you think?

2022-01-04 19:39 UTC, JoseCastroA commented on src/v2/entries.js
> +  }
@estebancordoba We need to cover all cases in each Tickspot endpoint.

In this case, we have some missing ways to get entries -> [GET entries](https://github.com/tick/tick-api/blob/master/sections/entries.md#get-entries)

2022-01-06 17:19 UTC, JoseCastroA commented on src/v2/entries.js
> +    return axios.get(
@estebancordoba To keep a structure in all requests, we should use async + await.

2022-01-06 21:48 UTC, estebancordoba commented on src/v2/entries.js
> +    return axios.get(
@JoseCastroA I think that in this case it is not necessary since the data is returned by then and catch, then the list function would become a promise

2022-01-06 21:48 UTC, estebancordoba commented on src/v2/entries.js
> +  }
@JoseCastroA should a new ticket be created for this? or does it already exist?
cc: @MarioRodriguezS

2022-01-12 22:48 UTC, JoseCastroA commented on src/v2/entries.js
> +    return axios.get(
@estebancordoba We agree to use async + await for readability. Anyway, if you think it is not necessary, we can discuss it with the rest of the team.

2022-01-12 22:50 UTC, JoseCastroA commented on src/v2/entries.js
> +  }
@estebancordoba All cases should be covered in this issue #30

2022-01-18 16:22 UTC, brayvasq reviewed
:wave: Hi @estebancordoba, thanks for this PR, nice work. Could you help me with some doubts I have? I left some comments.

2022-01-18 16:22 UTC, brayvasq commented on src/v2/entries.js
> +      });
@estebancordoba why do we use both `await` and `then`? I think we don't need the `then` block, because the await will resolve the data from axios, right?.

2022-01-18 16:22 UTC, brayvasq commented on src/v2/entries.js
> +    userId,
@estebancordoba This method should receive more params, right?

These params are optionals for this endpoint:
```
billable (true/false)
project_id
task_id
user_id
billed (true/false)
```

2022-01-26 20:53 UTC, estebancordoba commented on src/v2/entries.js
> +      });
@brayvasq I thought to use only then and catch but according to [this comment](https://github.com/kommitters/tickspot.js/pull/30#discussion_r783501256) I understood that due to the structure of the project we will use await

cc: @JoseCastroA

2022-01-26 21:55 UTC, estebancordoba commented on src/v2/entries.js
> +    userId,
you're right, I already added this, thanks!

2022-01-28 13:19 UTC, brayvasq approved these changes
:wave: Hi @estebancordoba, good job. Thanks for the contribution and for being patient about the changes :grin: .

2022-01-28 22:08 UTC, merged