#15 Create entries tickspot
kommitters/tickspot.js pull request #67
Opened 2021-12-06 22:16 UTC by MarioRodriguezS

## Description
In order to create the first method to the tickspot client was necessary to set the structure project and the structure tests. 

fix #15

2021-12-09 22:02 UTC, MarioRodriguezS commented
@brayvasq The comments were solved, at this moment is possible to call the methods through a client instance.

2021-12-13 15:30 UTC, brayvasq reviewed
@MarioRodriguezS Please update the README file with instructions on how to use the entries client.

2021-12-13 15:30 UTC, brayvasq commented on src/entries.js
> +    return dataCallback(response.data);
@MarioRodriguezS What if instead of call the function every time, we use a ternary operator, to check if there is a callback? something like this:
```javascript
return dataCallback ? dataCallback(response.data) : response.data;
```
What do you think?

2021-12-16 16:59 UTC, MarioRodriguezS commented on src/entries.js
> +    return dataCallback(response.data);
> @MarioRodriguezS What if instead of call the function every time, we use a ternary operator, to check if there is a callback? something like this:
> 
> ```js
> return dataCallback ? dataCallback(response.data) : response.data;
> ```
> 
> What do you think?

I agree, the comments were solved, thanks!

2021-12-16 21:44 UTC, brayvasq requested changes
@MarioRodriguezS Good Job :rocket:.  What if we put the code under the `src/v2/` folder? What do you think about that?

2021-12-16 21:44 UTC, brayvasq commented on test/fixture/entries/dataEntries.js
> +const dataEntryCreate = {
@MarioRodriguezS What if we rename it as `dataEntry`? What do you think?

2021-12-16 21:44 UTC, brayvasq commented on test/fixture/client.js
> +const infoUser = {
@MarioRodriguezS What if we rename it as `userInfo`?

2021-12-16 21:44 UTC, brayvasq commented on src/entries.js
> +      .catch((error) => error.response);
@MarioRodriguezS Please add a break line here.

2021-12-16 21:44 UTC, brayvasq commented on src/entries.js
> +    date,
@MarioRodriguezS  What happens if we don't send the `date` param or the `notes` param?

2021-12-16 21:44 UTC, brayvasq commented on src/client.js
> +  constructor({ subscriptionId, apiToken, agentEmail }) {
@MarioRodriguezS What happens if the user does not send those params?

2021-12-16 21:44 UTC, brayvasq commented on README.md
> +  taskId: 12345678,
@MarioRodriguezS Please format this code.

2021-12-16 21:44 UTC, brayvasq commented on README.md
> +  const dataCallback = (data) => data;
@MarioRodriguezS What if we add a more explicit example? I mean, show a function that performs a transformation on the data.

PD: Please add a break line.

2021-12-16 21:44 UTC, brayvasq commented on README.md
> +Include the client at your application
@MarioRodriguezS I think it's `in your application`.

2021-12-16 21:59 UTC, MarioRodriguezS commented on test/fixture/entries/dataEntries.js
> +const dataEntryCreate = {
I'm not sure if that could be enough descriptive, because the idea is to have all the data-Entries in the same file.

2021-12-16 22:01 UTC, MarioRodriguezS commented on src/entries.js
> +    date,
@brayvasq  In that case the entry will be created on the day of the request, and in the case of notes, the entry will not have notes.

2021-12-16 22:01 UTC, MarioRodriguezS commented on src/client.js
> +  constructor({ subscriptionId, apiToken, agentEmail }) {
@brayvasq The API will respond with the respective error.

2021-12-27 21:28 UTC, brayvasq approved these changes
:rocket:

2021-12-27 21:32 UTC, merged