#37 #31 little refactor and add list closed tasks method
kommitters/tickspot.js pull request #71
Opened 2022-02-01 22:54 UTC by brayvasq

Closes #37 #31 

# Description
:wave: Hello!. This PR contains some changes to the project structure and to tests structure. Those aren't heavy changes, Just saw some logic that was becoming common and repeated. Basically, the main changes of this PR are:
- Removed `dotenv` dependecy, since the configuration data are received at the moment the client is created.
- `tasks.js` and `entries.js` files were moved to the `resources` folder. Just to keep this specific client files in one place.
- Also, a `baseResource.js` file was created. It contains the `BaseResource` class that has a method called `makeRequest` which basically makes the requests to tickspot using axios.
- Some tests were created and moved to the `shared` folder, because they are common to most tests in the project.
- The `Tasks` class was added and the `listClosed` method was added to list all the closed tasks.
- The README of the project was updated.

What would be good to change in the future:
- [ ] README content related to project documentation should be split into separated files. The README file should only have the basic project info.
- [ ] Docs should include examples of responses for each method.
- [ ] Docs should include examples of responses when an error occurs.

### Feel free to add comments on this PR. Any comment, suggestion, advice, etc. is very welcome! :call_me_hand:

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2022-02-02 22:56 UTC, JoseCastroA requested changes

2022-02-02 22:56 UTC, JoseCastroA commented on src/v2/baseResource.js
> +      return response.status === 204;
@brayvasq What if we use `case` instead of `if`?

If you think it's not necessary, maybe we could use `if` or `case` in all files. Just to standardize.

2022-02-02 22:56 UTC, JoseCastroA commented on src/v2/resources/entries.js
> +   *    [Optional] userId, will be ignored if the user is not an administrator
@brayvasq At the end of some comments, there is a `dot .` And in the others, no. How about standardizing it?

2022-02-02 22:56 UTC, JoseCastroA commented on test/v2/baseResource.test.js
> +          }
@brayvasq Same in the tests, what if we use `case` instead of?

2022-02-02 22:56 UTC, JoseCastroA commented on test/v2/baseResource.test.js
> +        it(`Should also call axios.${method}`, async () => {
@brayvasq Running the tests, the `Describe` and `it` texts are concatenated, be careful with capital letters.

We should use downcase in any case, or capitalize just in the `Describe` text.

What do you think?

2022-02-02 22:56 UTC, JoseCastroA commented on test/v2/resources/entries/deleteEntry.test.js
> +    it('should return true ', async () => {
@brayvasq There is a space at the end of the text.

Also, all text in this test file is downcased, we could standardize it.

2022-02-02 22:56 UTC, JoseCastroA commented on test/v2/shared/responseCallback.js
> +    const succesfulResponse = responseFactory({
@brayvasq There are some misspelled words -> `successful`

2022-02-03 00:04 UTC, brayvasq commented
@JoseCastroA comments fixed. Also, I took the opportunity and moved some repeated logic to mock axios to some methods in `shared/utils/axios.js`.

2022-02-03 02:19 UTC, MrJuanGaviriaK commented on src/v2/baseResource.js
> +      case 'delete':
We should review this delete case because I think this case does not return anything when the entry is deleted and it should return true

2022-02-03 03:08 UTC, MrJuanGaviriaK requested changes
Hi, Brayan You made an excellent restructuring work. I left some comments. Thanks!

2022-02-03 03:08 UTC, MrJuanGaviriaK commented on test/v2/resources/tasks/listClosed.test.js
> +  authenticationErrorTests({
Do we need to test this authentication error for each case? What do you think if we only have one authentication test by resources(entries, tasks, etc... )?

2022-02-03 19:49 UTC, brayvasq commented on test/v2/resources/tasks/listClosed.test.js
> +  authenticationErrorTests({
:wave: I think this is a test case for each method as each method requires auth headers to make the request.

2022-02-03 21:31 UTC, estebancordoba reviewed
Good job @brayvasq! 👏 I left a comment as a possible improvement.

2022-02-03 21:31 UTC, estebancordoba commented on src/v2/baseResource.js
> +          .catch((error) => { throw new Error(`Request Error: ${error.response.status}`); });
I see that the function that handles the catch is similar in several requests, we could separate this one and reuse it, for example:
```const catchFunction = error => { throw new Error(`Request Error: ${error.response.status}`); };```
and use it in each catch like this:
```.catch(catchFunction);```

2022-02-07 23:15 UTC, brayvasq commented on src/v2/baseResource.js
> +          .catch((error) => { throw new Error(`Request Error: ${error.response.status}`); });
I agree, It's added now. Thanks :+1:

2022-02-07 23:18 UTC, brayvasq commented
@estebancordoba @MrJuanGaviriaK comments were solved. I also add a little example on how will look the responses of each method.

cc: @JoseCastroA

2022-02-08 00:09 UTC, estebancordoba approved these changes

2022-02-08 00:11 UTC, MrJuanGaviriaK approved these changes

2022-02-08 15:08 UTC, JoseCastroA approved these changes

2022-02-08 15:41 UTC, merged